### ISSUE TITLE
Fallo al validar cadenas que contienen un NIE válido dentro

### ISSUE THREAD

**Issue by leio10** [javiertoledo/spanish_vat_validators#3]
La validación falla si le pasas un valor como `'0X0000000T'`, ya que la expresión regular hace `match`, pero con una subcadena del valor recibido, y no garantiza que este empiece con una letra. Supongo que este bug también afecta a la validación de DNI y otros. Para resolverlo, creo que basta con poner `^` al principio de las expresiones regulares (supongo que de todas, aunque seguro que tú lo tendrás más claro) y el `$` al final. 

Ejemplo en el caso del NIE, línea 60:
```
return false unless value.match(/^[xyz][0-9]{7}[a-z]$/i)
```

**Comment by javiertoledo** [comment]
Gracias, los PRs son bienvenidos si te animas a arreglarlo :-)

**Comment by javiertoledo** [comment]
Fixed in PR #4
